#!/bin/sh

ROOT=..

ARGV0=$(basename $0)

TEST_1=0
TEST_2=0
TEST_3=0
TEST_4=0
TEST_5=0
TEST_6=0

usage()
{
    cat >&2 <<EOF
Usage: $ARGV0 N...
    N is a test number (from 1 to 6)
EOF
    exit 1
}


[ $# = 0 ] && usage

while :
do
    case "$1" in
	1 | 2 | 3 | 4 | 5 | 6 )
	    eval TEST_$1=1
	    ;;

	"" )
	    break
	    ;;

	* )
	    usage
	    ;;
    esac
    shift
done

    
if [ $TEST_1 = 1 ]
then
    $ROOT/test-1 -h -n mand.png mand-1-h-n.png
    $ROOT/test-1 -h -a mand.png mand-1-h-a.png
    $ROOT/test-1 -v -a -i mand.png mand-1-v-a_i.png
fi

if [ $TEST_2 = 1 ]
then
    $ROOT/test-2 -di -2 -a mand.png mand-2-di-2-a.png
    $ROOT/test-2 -di -3 -a mand.png mand-2-di-3-a.png
    $ROOT/test-2 -di -p -a mand.png mand-2-di-p-a.png
    $ROOT/test-2 -di -s -a mand.png mand-2-di-s-a.png
    $ROOT/test-2 -dj -s -a mand.png mand-2-dj-s-a.png
fi

if [ $TEST_3 = 1 ]
then
    $ROOT/test-3 -di -d 0.7 -a mand.png mand-3-di-d-07-a.png
    $ROOT/test-3 -di -d 2 -a mand.png mand-3-di-d-2-a.png
    $ROOT/test-3 -dj -d 0.7 -a mand.png mand-3-dj-d-07-a.png
    $ROOT/test-3 -dj -d 2 -a mand.png mand-3-dj-d-2-a.png
fi

if [ $TEST_4 = 1 ]
then
    $ROOT/test-4 -p mand.png mand-4-p.png
    $ROOT/test-4 -s  mand.png mand-4-s.png
    $ROOT/test-4 -d 0.7  mand.png mand-4-d07.png
    $ROOT/test-4 -d 2  mand.png mand-4-d2.png
fi

if [ $TEST_5 = 1 ]
then
    $ROOT/test-5 -p mand.png mand-5-p.png
    $ROOT/test-5 -s mand.png mand-5-s.png
    $ROOT/test-5 -d 0.7 mand.png mand-5-d07.png
    $ROOT/test-5 -d 2 mand.png mand-5-d2.png
fi

if [ $TEST_6 = 1 ]
then
    $ROOT/test-6 50 -i mand-5-s.png mand-6-s-th11.png 
    $ROOT/test-6 140 -i mand-5-s.png mand-6-s-th20.png 
    $ROOT/test-6 -h 50 140 -i mand-5-s.png mand-6-s-h11-20.png 
    
    $ROOT/test-6 5 -i mand-5-d07.png mand-6-d07-th11.png 
    $ROOT/test-6 10 -i mand-5-d07.png mand-6-d07-th20.png 
    $ROOT/test-6 -h 5 10 -i mand-5-d07.png mand-6-d07-h11-20.png 
    
    $ROOT/test-6 13 -i mand-5-d2.png mand-6-d2-th13.png 
    $ROOT/test-6 30 -i mand-5-d2.png mand-6-d2-th30.png 
    $ROOT/test-6 -h 13 30 -i mand-5-d2.png mand-6-d2-h13-30.png 
fi
